services:
  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile   # ← 後述の拡張入りPHPを使うのが安全
    image: my-php:8.3-fpm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: sched_u
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  adminer:            # ← services: の“中”に置く
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
